dir=/opt/openlist/data/temp
disk-cache=32M
file-allocation=none
continue=true
always-resume=false
max-resume-failure-tries=0
remote-time=true
auto-save-interval=20
force-save=false
max-tries=0
retry-wait=10
connect-timeout=10
timeout=10
max-concurrent-downloads=5
max-connection-per-server=16
split=16
min-split-size=4M
piece-length=1M
allow-piece-length-change=true
lowest-speed-limit=0
