[AutoRun]
enabled=false
runOnStartupAdded=false

[BitTorrent]
Session\DefaultSavePath=/opt/openlist/data/temp
Session\Port=6881
Session\TempPath=/opt/openlist/data/temp/incomplete

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Proxy\Engine=0

[Preferences]
Advanced\RecheckOnCompletion=false
Bittorrent\AddTrackersEnabled=false
Connection\PortRangeMin=6881
Downloads\PreAllocation=false
Downloads\SavePath=/opt/openlist/data/temp
Downloads\TempPath=/opt/openlist/data/temp/incomplete
Downloads\TempPathEnabled=true
General\Locale=vi_VN
MailNotification\enabled=false
WebUI\Address=127.0.0.1
WebUI\Port=8080
WebUI\Username=admin
WebUI\Password_PBKDF2="@ByteArray(2ZW+LuHuBQIP3FYZKPgcsg==:r11wm0gXwzFMIl0DSJjRfOHt0yU/nDV9rJcG08zgWmG6579L4IHfwc6ul7rOea0PLmCIRzmZG74tivByKMrpnA==)"
WebUI\CSRFProtection=true
WebUI\ClickjackingProtection=true
WebUI\SecureCookie=true
WebUI\LocalHostAuth=true
WebUI\MaxAuthenticationFailCount=9999
WebUI\BanDuration=0
