#!/bin/sh
exec 2>&1
HOME_DIR=/opt/openlist/data/service/qbittorrent
mkdir -p "$HOME_DIR/.config/qBittorrent" /opt/openlist/data/temp
export HOME="$HOME_DIR"
if [ ! -f "$HOME/.config/qBittorrent/qBittorrent.conf" ]; then
  cp /opt/mod/service/qbittorrent/qBittorrent.conf "$HOME/.config/qBittorrent/qBittorrent.conf"
fi
exec qbittorrent-nox --webui-port=8080
